<?php

declare(strict_types=1);

namespace RivetMSP\Mail;

/**
 * Decides whether an inbound message is machine generated (auto-reply, out-of-office, bounce, list mail, our own
 * notification looping back). Such mail must never create a ticket, add a reply or trigger an answer: replying to a
 * robot is how mail loops start. Pure: works on the parsed header map, no I/O.
 *
 * classify() returns null for ordinary mail, otherwise
 *   ['kind' => 'dsn'|'auto', 'rule' => <machine code>, 'detail' => <human text>]
 * kind 'dsn' is a delivery status notification (bounce); the caller still tells an admin about it.
 */
final class AutoReplyDetector
{
    /** Header present on every automated message this app sends (see cron/mail_queue.php). */
    public const LOOP_HEADER = 'x-rivetmsp-auto';

    /** The sibling edition's loop header: its notifications reaching this mailbox are just as automated. */
    public const SIBLING_LOOP_HEADERS = ['x-rivetit-auto'];

    /** Subject prefixes (after any Re:/AW:/SV: chain) that automated responders use. */
    private const OOO_SUBJECT = '/^\s*(?:(?:re|aw|sv|antw|vs|wg|fw|fwd|rv|r)\s*:\s*)*(?:'
        . 'auto(?:matic(?:ally)?)?[\s_-]*(?:reply|response|respuesta|antwort|svar|reponse)|automatic\s+reply'
        . '|out\s+of\s+(?:the\s+)?office|out-of-office|i\s+am\s+(?:currently\s+)?out\s+of\s+(?:the\s+)?office'
        . '|vacation\s+(?:reply|response|notice)|abwesenheit(?:snotiz)?|automatische\s+antwort'
        . '|r[eé]ponse\s+automatique|absence\s+du\s+bureau|hors\s+du\s+bureau|respuesta\s+autom[aá]tica|fuera\s+de\s+la\s+oficina'
        . '|risposta\s+automatica|fuori\s+sede|resposta\s+autom[aá]tica|fora\s+do\s+escrit[oó]rio|automatisch\s+antwoord|niet\s+aanwezig'
        . '|autosvar|fr[aå]nvarande|autoreply|auto-reply'
        . ')/iu';

    /** Subjects that identify a bounce even if the MIME structure was mangled. */
    private const DSN_SUBJECT = '/^\s*(?:(?:re|fw|fwd)\s*:\s*)*(?:undeliverable|undelivered\s+mail|delivery\s+status\s+notification|mail\s+delivery\s+(?:failed|failure|subsystem|system)|returned\s+mail|failure\s+notice|delivery\s+failure|mail\s+system\s+error|nicht\s+zustellbar|zustellung\s+fehlgeschlagen)/iu';

    /**
     * @param array<string, string[]> $headers lower-case name => values (RawHeaders::parse)
     * @param string[] $partContentTypes content types of every MIME part/attachment seen (for message/delivery-status)
     */
    public static function classify(array $headers, string $subject, array $partContentTypes = []): ?array
    {
        $first = static function (string $name) use ($headers): string {
            return trim((string) ($headers[$name][0] ?? ''));
        };

        // 1. Delivery status notifications first - they get their own, more useful, handling.
        $ctype = strtolower($first('content-type'));
        if (strpos($ctype, 'multipart/report') === 0 || strpos($ctype, 'report-type=delivery-status') !== false) {
            return ['kind' => 'dsn', 'rule' => 'dsn', 'detail' => 'multipart/report delivery status notification'];
        }
        foreach ($partContentTypes as $pt) {
            if (stripos((string) $pt, 'delivery-status') !== false) {
                return ['kind' => 'dsn', 'rule' => 'dsn', 'detail' => 'message/delivery-status part'];
            }
        }

        // 2. Our own automated mail coming back (loop).
        foreach (array_merge([self::LOOP_HEADER], self::SIBLING_LOOP_HEADERS) as $loop_header) {
            if (isset($headers[$loop_header])) {
                return ['kind' => 'auto', 'rule' => 'loop', 'detail' => 'Message carries ' . $loop_header . ' (generated by RivetMSP or RivetIT)'];
            }
        }

        // 3. RFC 3834 Auto-Submitted: anything except "no".
        if (isset($headers['auto-submitted'])) {
            $v = strtolower(trim(explode(';', $first('auto-submitted'))[0]));
            if ($v !== 'no') {
                return ['kind' => 'auto', 'rule' => 'auto_submitted', 'detail' => 'Auto-Submitted: ' . ($v === '' ? '(empty)' : $v)];
            }
        }

        // 4. Precedence: bulk / junk / list / auto_reply.
        $prec = strtolower($first('precedence'));
        if (in_array($prec, ['bulk', 'junk', 'list', 'auto_reply', 'auto-reply'], true)) {
            return ['kind' => 'auto', 'rule' => 'precedence', 'detail' => 'Precedence: ' . $prec];
        }

        // 5. Exchange's explicit "do not auto-respond" flags. DR/RN/NRN only concern receipts, so they do not count.
        if (isset($headers['x-auto-response-suppress'])) {
            $v = strtolower($first('x-auto-response-suppress'));
            if (preg_match('/\b(all|oof|autoreply)\b/', $v)) {
                return ['kind' => 'auto', 'rule' => 'auto_response_suppress', 'detail' => 'X-Auto-Response-Suppress: ' . $v];
            }
        }

        // 6. Vendor autoresponder headers.
        foreach (['x-autoreply', 'x-autorespond', 'x-auto-reply'] as $h) {
            if (isset($headers[$h])) {
                return ['kind' => 'auto', 'rule' => 'x_autoreply', 'detail' => $h . ' header present'];
            }
        }

        // 7. Null reverse path: an empty Return-Path (<>) is how bounces and many autoresponders are sent.
        if (isset($headers['return-path']) && preg_match('/^\s*<\s*>\s*$/', $first('return-path'))) {
            return ['kind' => 'auto', 'rule' => 'null_return_path', 'detail' => 'Return-Path is empty (<>)'];
        }

        // 8. Subject heuristics, last: they are the least precise signal.
        if (preg_match(self::DSN_SUBJECT, $subject)) {
            return ['kind' => 'dsn', 'rule' => 'dsn_subject', 'detail' => 'Bounce-style subject'];
        }
        if (preg_match(self::OOO_SUBJECT, $subject)) {
            return ['kind' => 'auto', 'rule' => 'ooo_subject', 'detail' => 'Out-of-office / auto-reply subject'];
        }

        return null;
    }
}
